name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            linux-musl,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/chopper
            asset_name: chopper-linux
          - name: linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: target/x86_64-unknown-linux-musl/release/chopper
            asset_name: chopper-linux-musl
            use_cross: true
          - name: macos
            os: macos-latest
            artifact_name: target/release/chopper
            asset_name: chopper-macos

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install Cross
      if: matrix.use_cross
      run: |
        cargo install cross --git https://github.com/cross-rs/cross

    # Standard build for non-musl targets
    - name: Build (Standard)
      if: '!matrix.use_cross'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release ${{ matrix.target && format('--target {0}', matrix.target) || '' }} --locked

    # Cross build for musl target
    - name: Build (Cross)
      if: matrix.use_cross
      run: |
        cross build --target ${{ matrix.target }} --release --locked

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}